apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-node-deployment
  namespace: devops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-node
  template:
    metadata:
      labels:
        app: back-node
    spec:
      containers:
      - name: back-node
        image: cristianbenavides/back-node:latest  # Imagen del backend en DockerHub
        ports:
        - containerPort: 8001