apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend-deployment
  namespace: devops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-backend
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
      - name: nodejs-backend
        image: cristianbenavides/back-node:latest  # Imagen del backend en DockerHub
        ports:
        - containerPort: 8001