apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-service
  namespace: devops-dev
spec:
  selector:
    app: fastapi-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000  # Cambia este puerto si necesitas otro disponible entre 30000 y 32767
  type: NodePort