apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend-deployment
  namespace: devops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
      - name: fastapi-backend
        image: cristianbenavides/fastapi-backend:latest  # Imagen del backend en DockerHub
        ports:
        - containerPort: 8000