apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: devops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
      - name: fastapi-backend
        image: cristianbenavides/fastapi-backend:latest
        env:
        - name: DATABASE_URL
          value: "mysql://root:@mysql-service:3306/dbusers"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend
  namespace: devops-dev
spec:
  selector:
    app: fastapi-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer