apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend-service
  namespace: devops-dev
spec:
  selector:
    app: nodejs-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
      nodePort: 30001  # Cambia este puerto si necesitas otro disponible entre 30000 y 32767
  type: NodePort